name: schedora
region: nyc
build:
  docker_context: .
  dockerfile: Dockerfile.backend

http:
  route: /
  port: 8080
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - "*"
    allow_headers:
      - "*"

env:
  - key: PORT
    value: 8080
