[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  REACT_APP_BACKEND_URL = "https://sechdora.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
